name: Build

on: [push, pull_request]

jobs:
  build:
    name: go-lingo
    runs-on: ubuntu-latest
    steps:
    - id: go
      uses: actions/setup-go@v1
      with:
        version: 1.13
    - uses: actions/checkout@v2
      with:
        path: ${{ steps['go'].module-path }}
    - name: Build
      working-directory: ${{ steps['go'].module-path }}
      run: make
    - name: Test
      working-directory: ${{ steps['go'].module-path }}
      run: make test
