name: Go CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - id: go
      uses: actions/setup-go@v1     
      with:
        version: 1.12

    - uses: actions/checkout@master
      with:
        path: ${{ steps['go'].module-path }}

    - name: Build
      working-directory: ${{ steps['go'].module-path }}
      run: make
      
    - name: Test
      working-directory: ${{ steps['go'].module-path }}
      run: make test
